services:

  rag:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: rag
    environment:
      - GEMINI_API_KEY=AIzaSyDIzrNgBHchsVObA7vBF5UQN1zbTv5PwJ0
    command: uvicorn app:app --host 0.0.0.0 --port 443
    restart: always
    ports:
      - "8443:443"

    volumes:
      - ../fastembed_cache:/tmp/fastembed_cache
      - ../models/:/root/.cache/datalab/models
      - ../huggingface_cache:/root/.cache/huggingface
      - .:/usr/src/app/
    networks:
      - rag
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "4317:4317"
      - "6006:6006"
    networks:
      - rag
networks:
  rag:
    external: true